import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>StageView - TimeBravo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          StageView - TimeBravo
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/TimeBravo/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/timebravoIcon.ico" alt="TimeBravo Logo" width={32} height={32} />
          </span>TimeBravo
        </a>
      </footer>
    </div >
  )
}
